version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: ["/start-reload.sh"]
    volumes:
      - ./backend:/app

  frontend:
    stdin_open: true
    working_dir: /app
    image: node:alpine
    command: ["yarn", "run", "start"]
    volumes:
      - ./frontend:/app

  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    container_name: nginx
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
