version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "80:80"
    restart: always
